[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vpn"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["click", "questionary", "rich"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
vpn = ["vpn.yml"]

[project.scripts]
vpn = "vpn:cli"
