services:
  epoxy:
    image: EPOXY_IMAGE_REF
    container_name: epoxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "127.0.0.1:8000:8000/tcp"
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY:-}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES:-}
      - OPENVPN_USER=${OPENVPN_USER:-}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:-}
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"apikey","apikey":"${HTTP_CONTROL_SERVER_API_KEY:-}"}
      - FIREWALL=on
      - WIREGUARD_MTU=1420
      - PUBLICIP_TIMEOUT=10s
      - DOT=off
      - DNS_PLAINTEXT_ADDRESS=1.1.1.1
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-}
      - SERVER_CITIES=${SERVER_CITIES:-}
    restart: always
